const nodemailer = require("nodemailer")
const { SMTP_HOST, SMTP_PORT, SECURE, EMAIL, PASSWORD } = require('../config/keys').EMAIL_CONFIG


async function main({ toEmails, subject, text }) {

    let transporter = nodemailer.createTransport({
        host: SMTP_HOST || "smtp.freesmtpservers.com",
        port: SMTP_PORT || 25,
        secure: SECURE,
        auth: {
            user: EMAIL || "sender@drlnetwork.com",
            pass: PASSWORD,
        },
    });

    // send mail with defined transport object
    let info = await transporter.sendMail({
        from: `"DRL Network" <${EMAIL}>`,
        to: toEmails,
        subject: subject,
        text: text,
        html: "",
    })

    console.log("Message sent: %s", info.messageId)
    return info.messageId
}

exports.sendMail = async ({ toEmails, subject, text })=>{
    return true
    // to handle array of emails or single email string
    toEmails = typeof toEmails == "object" ? toEmails.join(',') : toEmails

    await main({ toEmails, subject, text })
    return "Email sent to " + toEmails
}

exports.EMAIL_TEMPLATES = {
    SEND_PASSWORD_TEMPLATE: ({ firstName, password })=>{
        return {
            subject: 'Autogenerated for DRL Network',
            text: `
Hello ${firstName},

Thank you for registering into DRL Network.
Here is your password : ${password}

Regards,
DRL Network
`
        }
    }
}
